---
title: "Delhi transport data"
output: html_notebook
---


```{r}
#libraries used
library(data.table)
library(ggplot2)
library(plotly)
library(shiny)
#for ggplot graph side by side
library(cowplot)
#install.packages("cowplot")
```


```{r}
routs<-fread("routes.txt")
agency<-fread("agency.txt")
calendar<-fread("calendar.txt")
shapes<-fread("shapes.txt")
stop_times<-fread("stop_times.txt")
stops<-fread("stops.txt")
trips<-fread("trips.txt")
```

```{r}
final_data<-merge(merge(merge(stop_times,stops, by.x="stop_id", by.y="stop_id"),trips, by.x="trip_id", by.y="trip_id"),routs,by.x="route_id", by.y="route_id")
final_data$route_short_name<-NULL
```

```{r}
library(ggplot2)
theme_set(theme_bw())

par(mfrow=c(1,2))
# Top 5
x<-ggplot(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5], aes(x=as.factor(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5]$route_id), y=final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5]$sum)) + 
  geom_bar(stat="identity", width=.5, fill="skyblue") + 
  labs(title="Top 5 Routes",
       #subtitle="frequency plot",
       x='Route_ID',
       y='Number of Trips',
       subtitle="Number of trips per Routes", 
       caption="") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))+geom_text(aes(label=final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5]$sum), vjust=-0.3, size=3.5)+scale_y_continuous(labels=scales::comma)
x
# Least 5
y<-ggplot(tail(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)],5), aes(x=as.factor(tail(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)],5)$route_id), y=tail(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)],5)$sum)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Least 5 Routes",
       #subtitle="frequency plot",
       x='Route_ID',
       y='Number of Trips',
       subtitle="Number of trips per Routes", 
       caption="") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))+geom_text(aes(label=tail(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)],5)$sum), vjust=-0.3, size=3.5)+scale_y_continuous(labels=scales::comma)

#plot_grid(x,y)
#x
y
```
```{r}
head(final_data,3)
```

```{r}
final_data[,c("stop_name","route_id")][, .(number_of_distinct_orders = length(unique(route_id))), by = list(stop_name)][order(-number_of_distinct_orders)][0:5]
```

```{r}
final_data
```

```{r}
library(ggplot2)
theme_set(theme_bw())

par(mfrow=c(1,2))
# Top 5
x<-ggplot(final_data[,c("stop_name","route_id")][, .(number_of_distinct_orders = length(unique(route_id))), by = list(stop_name)][order(-number_of_distinct_orders)][0:5], aes(x=as.factor(final_data[,c("stop_name","route_id")][, .(number_of_distinct_orders = length(unique(route_id))), by = list(stop_name)][order(-number_of_distinct_orders)][0:5]$stop_name), y=final_data[,c("stop_name","route_id")][, .(number_of_distinct_orders = length(unique(route_id))), by = list(stop_name)][order(-number_of_distinct_orders)][0:5]$number_of_distinct_orders)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Top 5 Common Stations present in most of the routes",
       #subtitle="frequency plot",
       x='Stop Name',
       y='In Number of routes it occured',
       subtitle="", 
       caption="") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))+geom_text(aes(label=final_data[,c("stop_name","route_id")][, .(number_of_distinct_orders = length(unique(route_id))), by = list(stop_name)][order(-number_of_distinct_orders)][0:5]$number_of_distinct_orders), vjust=-0.3, size=3.5)+scale_y_continuous(labels=scales::comma)
x

# Least 5
#y<-ggplot(tail(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)],5), #aes(x=as.factor(tail(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)],5)$route_id), #y=tail(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)],5)$sum)) + 
#  geom_bar(stat="identity", width=.5, fill="tomato3") + 
#  labs(title="Least 5 Routes",
       #subtitle="frequency plot",
#       x='Route_ID',
#      y='Number of Trips',
#       subtitle="Number of trips per Routes", 
#       caption="") + 
#  theme(axis.text.x = element_text(angle=65, #vjust=0.6))+geom_text(aes(label=tail(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)],5)$sum), vjust=-0.3, #size=3.5)+scale_y_continuous(labels=scales::comma)

#plot_grid(x,y)
#x
#y

```

```{r}
final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5]
```


```{r}
ggplot(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5], aes(x=as.factor(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5]$route_id), y=final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5]$sum)) +
  geom_segment( aes(x=as.factor(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5]$route_id), xend=as.factor(final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5]$route_id), y=0, yend=final_data[,list(sum=length(unique(trip_id))),by=list(route_id)][order(-sum)][0:5]$sum), color="grey") +
  geom_point( color="orange", size=4) +
  theme_light() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_blank()
  ) +labs(title="Top 5 Routes",subtitle="frequency plot",x='Route_ID',y='Number of Trips', caption="") 
```

```{r}
final_data$arrival_time<-format(final_data$arrival_time, format="%H:%M:%S")
final_data$departure_time<-format(final_data$departure_time,format="%H:%M:%S")
```


```{r}
print("arrival time")
min(final_data$arrival_time)
max(final_data$arrival_time)

print("departure time")
min(final_data$departure_time)
max(final_data$departure_time)
```

```{r}
final_data[,list(min=min(arrival_time)),by=list(route_id,stop_name)][order(min)]
```

```{r}
final_data[,list(min=min(arrival_time)),by=list(route_id,stop_name)][order(min)]
```

